# Snakemake config
input:
output: 'plassembler_simulation_benchmarking.out/'
log: 'plassembler_simulation_benchmarking/plassembler_simulation_benchmarking.log'
threads: 16
# Snakemake Params

PLASSEMBLER_BIN : "/data/plassembler_benchmarking/plassembler/bin"
PLASSEMBLER_DB : "/data/plassembler_benchmarking/plassembler_db"



