"""
Database and output locations for the pipeline
"""




### OUTPUT DIRs
FLAGS = os.path.join(OUTPUT, 'FLAGS')

SR = os.path.join(OUTPUT, 'SR')
LR = os.path.join(OUTPUT, 'LR')

BENCHMARKS = os.path.join(OUTPUT, 'BENCHMARKS')

REAL = os.path.join(OUTPUT, 'REAL')
SIMULATED = os.path.join(OUTPUT, 'SIMULATED')
QUAST = os.path.join(OUTPUT, 'QUAST')

# plass
# real
PLASSEMBLER_OUTPUT_1_THREADS_REAL = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_1_THREADS')
PLASSEMBLER_OUTPUT_8_THREADS_REAL = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_8_THREADS')
PLASSEMBLER_OUTPUT_16_THREADS_REAL = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_16_THREADS')

# real with flye 


PLASSEMBLER_OUTPUT_1_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_1_THREADS_REAL_FLYE')
PLASSEMBLER_OUTPUT_8_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_8_THREADS_REAL_FLYE')
PLASSEMBLER_OUTPUT_16_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_16_THREADS_REAL_FLYE')

# sim
PLASSEMBLER_OUTPUT_1_THREADS_SIMULATED = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_1_THREADS')
PLASSEMBLER_OUTPUT_8_THREADS_SIMULATED = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_8_THREADS')
PLASSEMBLER_OUTPUT_16_THREADS_SIMULATED = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_16_THREADS')




# flye non deterministic
# PLASSEMBLER_OUTPUT_1_THREADS_NON_DET = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_1_THREADS_NON_DET')
# PLASSEMBLER_OUTPUT_8_THREADS_NON_DET = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_8_THREADS_NON_DET')
# PLASSEMBLER_OUTPUT_16_THREADS_NON_DET = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_16_THREADS_NON_DET')


# # raven
# RAVEN_OUTPUT_1_THREADS_REAL = os.path.join(REAL, 'RAVEN_OUTPUT_1_THREADS_REAL')
# RAVEN_OUTPUT_4_THREADS_REAL = os.path.join(REAL, 'RAVEN_OUTPUT_4_THREADS_REAL')
# RAVEN_OUTPUT_8_THREADS_REAL = os.path.join(REAL, 'RAVEN_OUTPUT_8_THREADS_REAL')
# RAVEN_OUTPUT_16_THREADS_REAL = os.path.join(REAL, 'RAVEN_OUTPUT_16_THREADS_REAL')

# unicycler
# real
UNICYCLER_OUTPUT_1_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_1_THREADS')
UNICYCLER_OUTPUT_8_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_8_THREADS')
UNICYCLER_OUTPUT_16_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_16_THREADS')

#sim
UNICYCLER_OUTPUT_1_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_1_THREADS')
UNICYCLER_OUTPUT_8_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_8_THREADS')
UNICYCLER_OUTPUT_16_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_16_THREADS')

# QUAST

# simulated
QUAST_PLASSEMBLER_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_16_THREADS')

# unicycler - need plasmids only

UNICYCLER_PLASMIDS_ONLY = os.path.join(QUAST, 'UNICYCLER_PLASMIDS_ONLY')
UNICYCLER_PLASMIDS_ONLY_1_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_REAL')


QUAST_UNICYCLER_1_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')

# real
QUAST_PLASSEMBLER_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_OUTPUT_16_THREADS')

UNICYCLER_PLASMIDS_ONLY_1_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_SIM')

QUAST_UNICYCLER_1_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')

# QUAST REFS

QUAST_REFS = os.path.join(QUAST, 'QUAST_REFS')


# ASSEMBLY LENGTHS

ASSEMBLY_LENGTHS = os.path.join(OUTPUT, 'ASSEMBLY_LENGTHS')
PLASSEMBLER_RAVEN_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_1_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_RAVEN_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_8_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_RAVEN_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_16_THREADS_OUTPUT_LENGTHS')


PLASSEMBLER_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_1_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_8_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_16_THREADS_OUTPUT_LENGTHS')

UNICYCLER_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_1_THREADS_OUTPUT_LENGTHS')
UNICYCLER_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_8_THREADS_OUTPUT_LENGTHS')
UNICYCLER_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_16_THREADS_OUTPUT_LENGTHS')
