"""
Database and output locations for the pipeline
"""




### OUTPUT DIRs
FLAGS = os.path.join(OUTPUT, 'FLAGS')

SR = os.path.join(OUTPUT, 'SR')
LR = os.path.join(OUTPUT, 'LR')

BENCHMARKS = os.path.join(OUTPUT, 'BENCHMARKS')

REAL = os.path.join(OUTPUT, 'REAL')
SIMULATED = os.path.join(OUTPUT, 'SIMULATED')
QUAST = os.path.join(OUTPUT, 'QUAST')

# plass
# raven

# real 
PLASSEMBLER_OUTPUT_1_THREADS_RAVEN = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_1_THREADS_RAVEN')
PLASSEMBLER_OUTPUT_8_THREADS_RAVEN = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_8_THREADS_RAVEN')
PLASSEMBLER_OUTPUT_16_THREADS_RAVEN = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_16_THREADS_RAVEN')

# sim
PLASSEMBLER_OUTPUT_1_THREADS_SIMULATED_RAVEN = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_1_THREADS_RAVEN')
PLASSEMBLER_OUTPUT_8_THREADS_SIMULATED_RAVEN = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_8_THREADS_RAVEN')
PLASSEMBLER_OUTPUT_16_THREADS_SIMULATED_RAVEN = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_16_THREADS_RAVEN')

# flye 
# real
PLASSEMBLER_OUTPUT_1_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_1_THREADS_FLYE')
PLASSEMBLER_OUTPUT_8_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_8_THREADS_FLYE')
PLASSEMBLER_OUTPUT_16_THREADS_REAL_FLYE = os.path.join(REAL, 'PLASSEMBLER_OUTPUT_16_THREADS_FLYE')

# simulated
PLASSEMBLER_OUTPUT_1_THREADS_SIMULATED_FLYE = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_1_THREADS_FLYE')
PLASSEMBLER_OUTPUT_8_THREADS_SIMULATED_FLYE = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_8_THREADS_FLYE')
PLASSEMBLER_OUTPUT_16_THREADS_SIMULATED_FLYE = os.path.join(SIMULATED, 'PLASSEMBLER_OUTPUT_16_THREADS_FLYE')


# unicycler
# real
UNICYCLER_OUTPUT_1_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_1_THREADS')
UNICYCLER_OUTPUT_8_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_8_THREADS')
UNICYCLER_OUTPUT_16_THREADS_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT_16_THREADS')

#sim
UNICYCLER_OUTPUT_1_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_1_THREADS')
UNICYCLER_OUTPUT_8_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_8_THREADS')
UNICYCLER_OUTPUT_16_THREADS_SIMULATED = os.path.join(SIMULATED, 'UNICYCLER_OUTPUT_16_THREADS')

###########################
# QUAST
##################

# QUAST REFS

QUAST_REFS = os.path.join(QUAST, 'QUAST_REFS')

# unicycler 
# directory holds the unicycler plasmids only to not overstate unicycler's inaccuracy

UNICYCLER_PLASMIDS_ONLY = os.path.join(QUAST, 'UNICYCLER_PLASMIDS_ONLY')
# real
UNICYCLER_PLASMIDS_ONLY_1_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_REAL')

# sim
UNICYCLER_PLASMIDS_ONLY_1_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_SIM')

# QUAST unicycler

QUAST_UNICYCLER_1_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')

QUAST_UNICYCLER_1_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')


# QUAST PLASSEMBLER FLYE

QUAST_PLASSEMBLER_FLYE_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_FLYE_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_FLYE_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# raven
QUAST_PLASSEMBLER_RAVEN_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_RAVEN_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_RAVEN_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')


#real
QUAST_PLASSEMBLER_FLYE_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_FLYE_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_FLYE_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# raven
QUAST_PLASSEMBLER_RAVEN_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_RAVEN_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_RAVEN_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')




# ASSEMBLY LENGTHS

ASSEMBLY_LENGTHS = os.path.join(OUTPUT, 'ASSEMBLY_LENGTHS')
RAVEN_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_1_THREADS_OUTPUT_LENGTHS')
RAVEN_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_8_THREADS_OUTPUT_LENGTHS')
RAVEN_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'RAVEN_16_THREADS_OUTPUT_LENGTHS')

PLASSEMBLER_RAVEN_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_RAVEN_1_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_RAVEN_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_RAVEN_8_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_RAVEN_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_RAVEN_16_THREADS_OUTPUT_LENGTHS')

PLASSEMBLER_FLYE_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_FLYE_1_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_FLYE_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_FLYE_8_THREADS_OUTPUT_LENGTHS')
PLASSEMBLER_FLYE_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'PLASSEMBLER_FLYE_16_THREADS_OUTPUT_LENGTHS')

FLYE_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'FLYE_1_THREADS_OUTPUT_LENGTHS')
FLYE_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'FLYE_8_THREADS_OUTPUT_LENGTHS')
FLYE_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'FLYE_16_THREADS_OUTPUT_LENGTHS')

UNICYCLER_1_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_1_THREADS_OUTPUT_LENGTHS')
UNICYCLER_8_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_8_THREADS_OUTPUT_LENGTHS')
UNICYCLER_16_THREADS_OUTPUT_LENGTHS = os.path.join(ASSEMBLY_LENGTHS, 'UNICYCLER_16_THREADS_OUTPUT_LENGTHS')
